name: create tag

on:
  push:
    branches:
      - master
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: determine semantic release
      run: |
        curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release
        chmod u=rx,g=,o= ./semantic-release
        ./semantic-release -vf --token ${{`{{ secrets.PERSONAL_GITHUB_TOKEN }}`}} --changelog CHANGELOG.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update CHANGELOG
        commit_user_name: Paytr0n
        commit_user_email: payron@tabetalt.no
        commit_author: Paytr0n <payron@tabetalt.no>
        file_pattern: CHANGELOG.md
        